# Miner name and version
MINER_NAME=cpuminer-rplant
MINER_VERSION=5.0.48

# Binary to run (from this folder)
MINER_BIN=cpuminer-ryzen

# HiveOS paths - usando la misma carpeta para el log
CUSTOM_LOG_BASENAME=/hive/miners/custom/cpuminer-rplant/cpuminer-rplant
CUSTOM_CONFIG_BASENAME=/hive/miners/custom/cpuminer-rplant
CUSTOM_CONFIG_FILENAME=$CUSTOM_CONFIG_BASENAME/cpuminer-rplant.conf

# Algorithm
CUSTOM_ALGO=yescryptr32
